# Generated by Django 3.0.5 on 2020-04-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='repo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='issues.Repo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='issues.Repo'),
            preserve_default=False,
        ),
    ]
