# Generated by Django 3.0.5 on 2020-04-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20200407_1856'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='issue',
            name='Issue_status_aaa4d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='issue',
            name='Issue_author__5e0ce2_idx',
        ),
        migrations.RemoveIndex(
            model_name='pullrequest',
            name='PullRequest_status_c93eb7_idx',
        ),
        migrations.RemoveIndex(
            model_name='pullrequest',
            name='PullRequest_author__743f8e_idx',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='pullrequest',
            old_name='status',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='opened_at',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='opened_at',
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['state'], name='Issue_state_5402c0_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['author', 'state'], name='Issue_author__251b71_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['state'], name='PullRequest_state_ffb35d_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['author', 'state'], name='PullRequest_author__4a2779_idx'),
        ),
    ]
