# Generated by Django 3.0.5 on 2020-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20200408_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
